Lotteri/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Lotteri.Models;

namespace Lotteri
{
    [Authorize]
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        [AllowAnonymous]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lotteri/Controllers/LotteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lotteri.Models;

namespace Lotteri.Controllers
{
    public class LotteriController : Controller
    {
        private readonly LotteriContext _context;

        public LotteriController(LotteriContext context)
        {
            _context = context;
        }

        // GET: Lotteri
        public async Task<IActionResult> Index()
        {
            return View(await _context.LottoItemModel.ToListAsync());
        }

        // GET: Lotteri/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lottoItemModel = await _context.LottoItemModel
                .SingleOrDefaultAsync(m => m.Id == id);
            if (lottoItemModel == null)
            {
                return NotFound();
            }

            return View(lottoItemModel);
        }

        // GET: Lotteri/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Lotteri/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,DateFrom,DateTo,IsVisible")] LottoItemModel lottoItemModel)
        {
            if (ModelState.IsValid)
            {
                _context.Add(lottoItemModel);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(lottoItemModel);
        }

        // GET: Lotteri/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lottoItemModel = await _context.LottoItemModel.SingleOrDefaultAsync(m => m.Id == id);
            if (lottoItemModel == null)
            {
                return NotFound();
            }
            return View(lottoItemModel);
        }

        // POST: Lotteri/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,DateFrom,DateTo,IsVisible")] LottoItemModel lottoItemModel)
        {
            if (id != lottoItemModel.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(lottoItemModel);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!LottoItemModelExists(lottoItemModel.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(lottoItemModel);
        }

        // GET: Lotteri/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var lottoItemModel = await _context.LottoItemModel
                .SingleOrDefaultAsync(m => m.Id == id);
            if (lottoItemModel == null)
            {
                return NotFound();
            }

            return View(lottoItemModel);
        }

        // POST: Lotteri/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var lottoItemModel = await _context.LottoItemModel.SingleOrDefaultAsync(m => m.Id == id);
            _context.LottoItemModel.Remove(lottoItemModel);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool LottoItemModelExists(int id)
        {
            return _context.LottoItemModel.Any(e => e.Id == id);
        }
    }
}

Lotteri/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

Lotteri/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

Lotteri/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "LotteriApplikation";
}

<div>
    <h2>Hej och välkommen till Lotteriapplikationen</h2>
    <p> denna applikation kan du skapa utlottningar av diverse saker.</p>
    <p> Användare kan sedan anmäla sig för utlottning och sedan drar appliktionen en slumpmässig vinnare</p>

    <table class="table">
        <tbody>
            <tr>
                <td>
                    <a asp-area="" asp-controller="Home" asp-action="Index">Hem</a>
                    <a asp-area="" asp-controller="Lotteri" asp-action="Index">Lotteri</a>
                    <a asp-area="" asp-controller="Anmalan" asp-action="Index">Anmälan</a>
                </td>
            </tr>
        </tbody>
    </table>

</div>